config/routes.rb
Rails.application.routes.draw do
  root 'vehicles#index'
  get 'vehicles/theme', to: 'vehicles#theme'
  #  post 'vehicles/reserve/', to: 'vehicles#reserve'
  get 'vehicles/reserve_form', to: 'vehicles#reserve_form'
  resources :users
  resources :vehicles do
    post 'reserve', on: :member #creates a custom => route vehicles/11/reserve
    # get 'reserve_form', on: :member #creates a custom => route vehicles/11/reserve_form
  end
  get 'vehicles/delete/candidates', to: 'vehicles#candidates'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
  validates :user, :vehicle, :name, :book_date, presence: true
  validates :user, uniqueness: { scope: :vehicle }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :themes
  has_many :vehicles, through: :themes
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :themes
  has_many :users, through: :themes
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :password, :email, :contact)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[show edit update destroy]

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET vehicles/theme
  def theme
    @user = User.find(1) # ! should change this user on add devise
    @vehicles = @user.vehicles # ! join table - has_many_through
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show; end

  # POST vehicles/1/reserve/
  def reserve
    @user = User.find(1) # ! change this to get the current user
    Theme.create(user_id: @user.id, vehicle_id: params[:vehicle_id], book_date: params[:date],
                 name: params[:vehicle_id], city: params[:city])
  end

  # GET /vehicles/reserve_form
  def reserve_form
    return unless params[:id].present?

    @vehicle = Vehicle.find(params[:id])
  end

  # GET /vehicles/delete/candidates
  def candidates
    @vehicles = Vehicle.all
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit; end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def vehicle_params
    params.require(:vehicle).permit(:name, :image, :drive_fee, :purchase_fee)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prestige</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# swiper cdn %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
</html>

app/views/partials/_nav.html.erb
<nav>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Theme vehicles", vehicles_theme_path %></li>
    <li><%= link_to "Reserve form", vehicles_reserve_form_path %></li>
    <li><%= link_to "My Reservations", new_vehicle_path %></li>
    <%# ! the links below will be admin links %>
    <li><%= link_to "Add Vehicle", new_vehicle_path %></li>
    <li><%= link_to "Delete Vehicles", vehicles_delete_candidates_path %></li>
  </ul>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :contact, style: "display: block" %>
    <%= form.text_field :contact %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= user.contact %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/vehicles/_delete.html.erb
  <div id="<%= dom_id vehicle %>">
    <div>
      <% if vehicle.image.present? %>
        <%= image_tag vehicle.image, class: 'vehicle-image', alt: 'My Image' %> 
      <% end %>
    </div>
    <p>
      <%= vehicle.name %>
    </p>
    <p>
      <%= vehicle.desc %>
    <p>
    <p>
        <%= button_to "Destroy", vehicle, method: :delete %>
    </p>
  </div>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, html: { class: "form-add-vehicle" }) do |form| %>
  <% if vehicle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% vehicle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "input"%>
  </div>

  <div>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :drive_fee, style: "display: block" %>
    <%= form.text_field :drive_fee, class: "input" %>
  </div>

  <div>
    <%= form.label :hire_fee, style: "display: block" %>
    <%= form.text_field :hire_fee, class: "input" %>
  </div>

  <div>
    <%= form.label :purchase_fee, style: "display: block" %>
    <%= form.text_field :purchase_fee, class: "input" %>
  </div>

  <div>
    <%= form.submit "Add vehicle", id: "submit" %>
  </div>
<% end %>

app/views/vehicles/_reserve.html.erb
<%= form_with(url: "vehicles/reserve", method: "post") do |form| %>

  <div>
    <%=form.label :name %>
    <%= form.text_field  :name, value: @vehicle.name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.select :city, options_for_select([['Kampala', 'KLA'], ['Lira', 'LR']]), { prompt: "Please select a city" }, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date, class: "form-control", value: Date.today, placeholder: "Choose a date", min: Date.today, max: Date.today + 1.year %> 
  </div>

    <%= hidden_field_tag :vehicle_id, @vehicle.id %>

  <%= form.submit "Reserve", class: " reserve" %>
<% end %>

app/views/vehicles/_theme.html.erb
<article class="swiper-slide">
  <%= link_to vehicle, class: "vehicle-link"  do %>
    <div id="<%= dom_id vehicle %>" class="card">
      <div class="mark">
        <%= image_tag(vehicle.image, class: 'vehicle-image', alt: 'My Image') %> 
      </div>
      <div class="vehicle-detail">
        <p><%= vehicle.name %></p>
        <p><%= vehicle.desc %><p>
        <p>Test Fee: <%= vehicle.drive_fee %><p>
        <p>Price: <%= vehicle.purchase_fee %><p>
      </div>
    </div>
  <% end %>
</article>

app/views/vehicles/_vehicle.html.erb
<div id="<%= dom_id vehicle %>">
  <%# <%= link_to "Show this vehicle", vehicle %>

<%# show vehicle image %>
  <div>
    <p>
      <strong>Image:</strong>
      <%= image_tag vehicle.image, class: 'vehicle-image', alt: 'My Image' %> 
    </p>
  </div>


<div>
  <p>
    <strong>Name:</strong>
    <%=image_tag vehicle.name %>
  </p>
  <p>
    <strong>Drive fee:</strong>
    <%= vehicle.drive_fee %>
  </p>

  <p>
    <strong>Purchase fee:</strong>
    <%= vehicle.purchase_fee %>
  </p>
</div>  

</div>

app/views/vehicles/candidates.html.erb
<p style="color: green"><%= notice %></p>

<h1>Vehicles for deletion</h1>
<div>
    <%= render "partials/nav" %>
</div>

<div id="vehicles">
  <% @vehicles.each do |vehicle| %>
    <%= render partial: "vehicles/delete", locals: { vehicle: vehicle } %> 
  <% end %>
</div>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to "Show this vehicle", @vehicle %> |
  <%= link_to "Back to vehicles", vehicles_path %>
</div>

app/views/vehicles/index.html.erb
<main class="wrapper">
  <div class="notice">
    <%= notice %> 
    <h1>Latest models</h1>
  </div>
  <section class="menu">
      <%= render "partials/nav" %>
  </section> 
  <section class="content">
    <div class="swiper"><!-- Slider main container -->
      <div class="swiper-wrapper"><!-- Additional required wrapper -->
        <% @vehicles.each do |vehicle| %>
          <%= render partial: "vehicles/theme", locals: { vehicle: vehicle } %><!-- Slides --> 
        <% end %>
      </div> 
      <!-- navigation buttons -->
      <div class="swiper-button-prev"></div> 
      <div class="swiper-button-next"></div>
    </div>
  </section>
</main>

app/views/vehicles/new.html.erb
<main class="wrapper">
  <div class="notice">
    <%= notice %> 
    <h1>Add vehicle</h1>
  </div>
  <section class="menu">
    <%= render "partials/nav" %>
    <div class="vehicles"><%= link_to "Back to vehicles", vehicles_path %></div>
  </section> 
  <section class="content">
   <%= render "form", vehicle: @vehicle %>
  </section>
</main>

app/views/vehicles/reserve_form.html.erb
<main class="wrapper">
  <div class="notice">
    <%= notice %> 
    <h1>Reserve vehicle</h1>
  </div>

  <section class="menu">
      <%= render "partials/nav" %>
  </section> 

  <section class="content">
    <%= render partial: "vehicles/reserve", locals: { user: @vehicle } %> 
  </section>
</main>

app/views/vehicles/show.html.erb
<main class="show-page">
  <section class="menu">
      <%= render "partials/nav" %>
  </section>
  <section class="middle-section">
    <%= image_tag @vehicle.image, class: 'vehicle-image', alt: 'My Image' %> 
  </section>
  <section class="details-pad">
    <article class="details">
      <div class="right-align">
        <h2><%= @vehicle.name%></h2>
        <p>- <%= @vehicle.desc %></p>
      </div>

      <ul>
        <li>
        <span>drive fee</span>
        <%= @vehicle.drive_fee%>
        </li>

        <li>
          <span>Purchase fee</span>
          <%= @vehicle.purchase_fee %>
        </li>

        <li>
        <span>Initial deposit</span>
        <%= 0.2*@vehicle.purchase_fee %>
        </li>

        <li>
        <span>Monthly installments</span>
        <%= 0.05*@vehicle.purchase_fee %>
        </li>

        <li>
          <span>Duration</span>
          <span><%= (@vehicle.purchase_fee - 0.2*@vehicle.purchase_fee)/(0.05*@vehicle.purchase_fee) %> months<span>
        </li>
      </ul>
    </article>


    <div class="control-group">
      <%= link_to "Edit", edit_vehicle_path(@vehicle), class: "control link edit" %> 
      <%= link_to "Vehicles", vehicles_path, class: "control link vehicles" %>
      <%= button_to "Delete", @vehicle, method: :delete, class: "control delete" %>
      <%= link_to "Reserve", vehicles_reserve_form_path(id: @vehicle.id), class: "control link reserve" %>
    </div>
  </section>
</main>

app/views/vehicles/theme.html.erb
<main class="wrapper">
<div class="notice">
    <%= notice %> 
    <h1>Theme vehicles</h1>
  </div>

  <section class="menu">
      <%= render "partials/nav" %>
  </section>

  <section class="content">
    <div class="swiper">
      <div class="swiper-wrapper">
        <% @vehicles.each do |vehicle| %>
            <%= render partial: "vehicles/theme", locals: { vehicle: vehicle } %>
        <% end %>
      </div>
      <div class="swiper-button-prev"></div> 
      <div class="swiper-button-next"></div>
    </div>
  </section>

</main>